language: ruby
rvm:
- 1.9.3
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
addons:
  code_climate:
    repo_token:
      secure: SA6b9tTkurbLH7+rcIMJm3X9kKEYsB5eHy9IfP/D3cT/7seDfLseXfredybt4cSJQMZRzr1+yu3vcF2YNvfoBD4u16s1WizUvsKByqoSx/o9q4ou1c9rSEtEB9kR2yMR3jUoZavcDObgpUM27Ea8aaij7Oe0J0rvqu/+ij8GqPQ=
